---
title: "CUNY SPS MSDS D607 Project 1"
author: "Keith Colella"
date: "`r Sys.Date()`"
output: html_document
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../D607/output"
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(stringr)
```

## Title

```{r}
txt <- read_file(paste0('https://raw.githubusercontent.com/kac624/',
                        'cuny/main/D607/data/tournamentinfo.txt'))
```

## TBD

```{r}
txt2 <- str_replace_all(txt, c('\n'=''))

locations <- str_locate_all(txt2, paste(replicate(89, "-"), 
                                       collapse = "")
                            )[[1]]

df <- data.frame(matrix(ncol = 4, nrow = 0))
x <- c('name', 'state', 'total_pts', 'pre_rating')
colnames(df) <- x
```

## TBD

```{r}
for (i in 1:nrow(locations) - 1) {
  row <- str_sub(txt2, locations[i,2] + 1, locations[i+1,1] - 1)
  name <- trimws(str_match(row, '[0-9] \\| (.*?) \\|[0-9]')[,2])
  state <- str_match(row, ' ([A-Z]{2}) \\| [0-9]')[,2]
  total_pts <- str_match(row, '\\|([0-9]\\.[0-9])  \\|')[,2]
  pre_rating <- str_match(row, 'R:( |  )([0-9]+|[0-9]+P[0-9])')[,3]
  df[i, ] <- c(name, state, total_pts, pre_rating)
}
```