---
title: "Election Tweets 2022 - Partisanship and Competitiveness"
author: "Keith Colella"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, message = FALSE}
library(tidyverse)
library(infer)
library(tigris)
library(sf)
library(kableExtra)
library(cowplot)

set.seed(888)
```

## Data

Primary data

```{r}
candidates <- read_csv('data/candidates_partisan_compete.csv')

glimpse(candidates)

candidates <- candidates %>%
  mutate(moc = if_else(is.na(bioguide_id), 'No', 'Yes')) %>%
  select(name, state, district, party, incumbent_challenge, moc,
         contains('partisan'), contains('compete'))

candidates <- candidates[!duplicated(candidates),]

candidates[duplicated(candidates$name) | duplicated(candidates$name, fromLast = TRUE),]
```

Mapping Data

```{r}
data('fips_codes')

districts_sf <- congressional_districts() %>% 
  st_simplify(dTolerance = 10000) %>%
  data.frame() %>%
  left_join(
    fips_codes %>%
      select(state, state_code) %>%
      unique(), 
    by = c('STATEFP' = 'state_code')
  )

states_sf <- states(cb = TRUE) %>% 
  st_simplify(dTolerance = 1000) %>%
  data.frame() %>%
  filter(STUSPS != 'AS',
         STUSPS != 'GU',
         STUSPS != 'MP',
         STUSPS != 'VI',
         STUSPS != 'PR',)

candidates_sf <- candidates %>%
  left_join(
    select(districts_sf, state, CD116FP, geometry),
    by = c('state', 'district' = 'CD116FP'),
  ) %>%
  left_join(
    select(states_sf, STUSPS, geometry), suffix = c('_distr','_state'),
    by = c('state' = 'STUSPS')
  )
```

## EDA

Spread across states

```{r}
state_bar_plot <- function (data, filter_column) {
  data %>%
    mutate(dupe = duplicated(name)) %>%
    filter(!is.na(!! sym(filter_column)),
           dupe == FALSE) %>%
    group_by(state) %>% 
    summarise(count = n()) %>% 
    ggplot(aes(x = reorder(state, count), y = count)) +
    geom_bar(stat = 'identity') +
    scale_x_discrete(guide = guide_axis(n.dodge = 3)) +
    xlab(filter_column) +
    coord_flip()
}

state_plots <- lapply(c('name','partisan_score_twitter',
                        'partisan_score_nominate','partisan_score_govtrack'), 
                      state_bar_plot, data = candidates)

plot_grid(plotlist = state_plots, nrow = 2, ncol = 2)
```

Spread across parties

```{r}
party_bar_plot <- function (data, filter_column) {
  data %>%
    mutate(dupe = duplicated(name)) %>%
    filter(!is.na(!! sym(filter_column)), dupe == FALSE,
           party == 'DEMOCRATIC PARTY' | party == 'REPUBLICAN PARTY') %>%
    group_by(party) %>% 
    summarise(count = n()) %>% 
    ggplot(aes(x = reorder(party, count), y = count)) +
    geom_bar(stat = 'identity') +
    xlab(filter_column)
}

party_plots <- lapply(c('name','partisan_score_twitter',
                        'partisan_score_nominate','partisan_score_govtrack'), 
                      party_bar_plot, data = candidates)

plot_grid(plotlist = party_plots, nrow = 2, ncol = 2)
```

Geographic Visualization

```{r}
candidates_sf %>%
  filter(state != 'HI',
         state != 'AK',
         state != 'PR') %>%
  ggplot() + 
  geom_sf(aes(geometry = geometry_distr, fill = compete_ideology)) +
  geom_sf(aes(geometry = geometry_state), color = 'blue', size = 0.4, fill = NA) +
  scale_fill_gradient(low = 'gray100', 
                      high = 'purple') + 
  theme(legend.position='bottom')

candidates_sf %>%
  filter(state != 'HI',
         state != 'AK',
         state != 'PR') %>%
  ggplot() + 
  geom_sf(aes(geometry = geometry_distr, fill = compete_cookpvi)) +
  geom_sf(aes(geometry = geometry_state), color = 'blue', size = 0.4, fill = NA) +
  scale_fill_gradient(low = 'gray100', 
                      high = 'purple') + 
  theme(legend.position='bottom')

candidates_sf %>%
  filter(state != 'HI',
         state != 'AK',
         state != 'PR') %>%
  ggplot() + 
  geom_sf(aes(geometry = geometry_distr, fill = compete_eff_gap)) +
  geom_sf(aes(geometry = geometry_state), color = 'blue', size = 0.4, fill = NA) +
  scale_fill_gradient(low = 'gray100', 
                      high = 'purple') + 
  theme(legend.position='bottom')
```

Efficiency and Partisanship

```{r}
scatterplot <- function(x,y) {
  candidates %>%
  filter(!is.na(!! sym(x)),
         !is.na(!! sym(y))) %>%
  ggplot(aes(x = !! sym(x), y = !! sym(y))) +
  geom_point() +
  geom_smooth(method = 'lm', formula = 'y ~ x') +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 10)) +
  labs(title = str_c(str_remove_all(x, 'compete|_'), '-',
                     str_remove_all(y, 'partisan_score|_')))
}

var_grid <- expand_grid(
  x = colnames(select(candidates, contains('compete'))),
  y = colnames(select(candidates, contains('partisan')))
)

plot_list <- list()

for (row in 1:nrow(var_grid)) {
  plot <- scatterplot(as.character(var_grid[row,'x']),
                      as.character(var_grid[row,'y']))
  plot_list[[row]] <- plot
}

plot_grid(plotlist = plot_list, nrow = 3, ncol = 3)
```

Summary Stats

```{r}
cat('District Ideology\n')
summary(candidates$compete_ideology)
cat('\nDistrict Cook PVI\n')
summary(candidates$compete_cookpvi)
cat('\nDistrict Effiency Gap\n')
summary(candidates$compete_eff_gap)
```

Binary Independent Variables

```{r}
candidates <- candidates %>%
  mutate(
    compete_ideology_binary = if_else(compete_ideology > median(
      candidates$compete_ideology, na.rm = TRUE), 'high', 'low'),
    compete_cookpvi_binary = if_else(compete_cookpvi > median(
      candidates$compete_cookpvi, na.rm = TRUE), 'high', 'low'),
    compete_eff_gap_binary = if_else(compete_eff_gap > median(
      candidates$compete_eff_gap, na.rm = TRUE), 'high', 'low'))

boxplot <- function(x,y) {
  candidates %>%
  filter(!is.na(!! sym(x)),
         !is.na(!! sym(y))) %>%
  ggplot(aes(x = !! sym(x), y = !! sym(y))) +
  geom_boxplot() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 10)) +
  labs(title = str_c(str_remove_all(x, 'compete|_|binary'), '_',
                     str_remove_all(y, 'partisan_score|_')))
}

var_grid <- expand_grid(
  x = colnames(select(candidates, (contains('compete') & contains('binary')))),
  y = colnames(select(candidates, contains('partisan')))
)

plot_list <- list()

for (row in 1:nrow(var_grid)) {
  plot <- boxplot(as.character(var_grid[row,'x']),
                  as.character(var_grid[row,'y']))
  plot_list[[row]] <- plot
}

plot_grid(plotlist = plot_list, nrow = 3, ncol = 3)
```

## Hypothesis Test

Define functions

```{r}
hyp_diff_means <- function(x, y, 
                           data = candidates,
                           conf_level = 0.95, 
                           bootstraps = 1000) {
  mean_diff <- data %>%
    filter(!is.na(!! sym(y)),
           !is.na(!! sym(x))) %>%
    specify(response = (!!sym(y)), explanatory = (!!sym(x))) %>%
    calculate(stat = 'diff in means', order = c('high', 'low'))
  
  null_dist <- data %>%
    filter(!is.na(!! sym(y)),
           !is.na(!! sym(x))) %>%
    specify(response = (!!sym(y)), explanatory = (!!sym(x))) %>%
    hypothesize(null = 'independence') %>%
    generate(reps = bootstraps, type = 'permute') %>%
    calculate(stat = 'diff in means', order = c('high', 'low'))
  
  pval <- null_dist %>% 
    get_p_value(obs_stat = mean_diff, direction = 'two-sided')
  
  ci <- data %>%
    filter(!is.na(!! sym(y)),
           !is.na(!! sym(x))) %>%
    specify(response = (!!sym(y)), explanatory = (!!sym(x))) %>%
    generate(reps = bootstraps, type = 'bootstrap') %>%
    calculate(stat = 'diff in means', order = c('high', 'low')) %>%
    get_ci(level = conf_level)
  
  results <- list(p_value = pval$p_value,
                  lower_ci = ci$lower_ci,
                  upper_ci = ci$upper_ci)
  
  return(results)
}

grid_hyp_test <- function(data, grid) {
  
  results_df <- data.frame(grid, p_value = NA, lower_ci = NA, upper_ci = NA)
  
  for (row in 1:nrow(grid)) {
    
    test_name <- str_c(str_remove_all(as.character(grid[row,'x']),
                                      'compete|_|binary'), '_',
                       str_remove_all(as.character(grid[row,'y']),
                                      'partisan_score|_'))
    
    result <- hyp_diff_means(as.character(grid[row,'x']),
                             as.character(grid[row,'y']),
                             data = data)
    
    results_df <- results_df %>%
      mutate(
        p_value = replace(p_value,
                          x == as.character(grid[row,'x']) &
                            y == as.character(grid[row,'y']),
                          result$p_value),
        lower_ci = replace(lower_ci,
                           x == as.character(grid[row,'x']) &
                             y == as.character(grid[row,'y']),
                           result$lower_ci),
        upper_ci = replace(upper_ci,
                           x == as.character(grid[row,'x']) &
                             y == as.character(grid[row,'y']),
                           result$upper_ci))
  }
  
  return(results_df)
  
}

hyp_test_heatmap <- function(results_df) {
  results_df %>%
    mutate(x = str_remove_all(x, 'compete|binary|_'),
           y = str_remove_all(y, 'partisan_score|_')) %>% 
    ggplot(aes(x, y)) +
               # factor(x, levels = c('cookpvi','ideology','effgap')), 
               # factor(y, levels = c('twitter','govtrack','nominate')))) +
    geom_tile(aes(fill = p_value)) +
    geom_text(aes(label = str_c('p-value: ',
                                if_else(p_value == 0, '<0.000', 
                                        format(round(p_value,3), nsmall=3)),
                                '\n95% CI: ',round(lower_ci,3),
                                ' to ',round(upper_ci,3)))) +
    xlab('District Competition Measures') +
    ylab('Candidate Partisanship Measures') +
    theme(axis.text.y = element_text(angle = 90, hjust = 0.5)) +
    scale_fill_gradient(low = 'darkslategray1', 
                        high = 'gray100',
                        limits = c(0,0.1),
                        oob = scales::squish)
}
```

Run test on full data

```{r}
results <- grid_hyp_test(data = candidates, grid = var_grid)
hyp_test_heatmap(results)
```

Split by party

```{r}
results_dem <- grid_hyp_test(data = filter(candidates,
                                           party == 'DEMOCRATIC PARTY'), 
                             grid = var_grid)
hyp_test_heatmap(results_dem)

results_rep <- grid_hyp_test(data = filter(candidates,
                                           party == 'REPUBLICAN PARTY'), 
                             grid = var_grid)
hyp_test_heatmap(results_rep)
```

By Candidate Status

```{r}
results_incumb <- grid_hyp_test(data = filter(candidates,
                                              incumbent_challenge == 'Incumbent'), 
                                grid = filter(var_grid,
                                              str_detect(y, 'twitter')))
hyp_test_heatmap(results_incumb)

results_chall <- grid_hyp_test(data = filter(candidates,
                                              incumbent_challenge == 'Challenger'), 
                                grid = filter(var_grid,
                                              str_detect(y, 'twitter')))
hyp_test_heatmap(results_chall)

results_open <- grid_hyp_test(data = filter(candidates,
                                              incumbent_challenge == 'Open seat'), 
                                grid = filter(var_grid,
                                              str_detect(y, 'twitter')))
hyp_test_heatmap(results_open)
```

No MOCs

```{r}
results_noMOC <- grid_hyp_test(data = filter(candidates,
                                             moc == 'No'), 
                                grid = filter(var_grid,
                                              str_detect(y, 'twitter')))
hyp_test_heatmap(results_noMOC)
```

## ANOVA

Quartile split

```{r}
candidates <- candidates %>%
  mutate(
    compete_ideology_discrete = factor(
      case_when(compete_ideology < summary(candidates$compete_ideology)[2] ~ 1,
                compete_ideology < summary(candidates$compete_ideology)[3] ~ 2,
                compete_ideology < summary(candidates$compete_ideology)[5] ~ 3,
                compete_ideology >= summary(candidates$compete_ideology)[5] ~ 4,
                TRUE ~ NA), levels = c(1,2,3,4), ordered = TRUE),
    compete_cookpvi_discrete =factor(
      case_when(compete_cookpvi < summary(candidates$compete_cookpvi)[2] ~ 1,
                compete_cookpvi < summary(candidates$compete_cookpvi)[3] ~ 2,
                compete_cookpvi < summary(candidates$compete_cookpvi)[5] ~ 3,
                compete_cookpvi >= summary(candidates$compete_cookpvi)[5] ~ 4,
                TRUE ~ NA), levels = c(1,2,3,4), ordered = TRUE),
    compete_eff_gap_discrete = factor(
      case_when(compete_eff_gap < summary(candidates$compete_eff_gap)[2] ~ 1,
                compete_eff_gap < summary(candidates$compete_eff_gap)[3] ~ 2,
                compete_eff_gap < summary(candidates$compete_eff_gap)[5] ~ 3,
                compete_eff_gap >= summary(candidates$compete_eff_gap)[5] ~ 4,
                TRUE ~ NA), levels = c(1,2,3,4), ordered = TRUE))

var_grid_discrete <- data.frame(
  x = var_grid$x %>%
    str_replace_all('_binary','_discrete'),
  y = var_grid$y %>%
    str_replace_all('_binary','_discrete'))

plot_list <- list()

for (row in 1:nrow(var_grid_discrete)) {
  plot <- boxplot(as.character(var_grid_discrete[row,'x']),
                  as.character(var_grid_discrete[row,'y']))
  plot_list[[row]] <- plot
}

plot_grid(plotlist = plot_list, nrow = 3, ncol = 3)
```

Assumptions

```{r}
for (row in 1:nrow(var_grid_discrete)) {
  x = as.character(var_grid_discrete[row,'x'])
  y = as.character(var_grid_discrete[row,'y'])
  candidates %>%
    group_by(!!sym(x)) %>%
    summarize(std_dev = sd(!!sym(y), na.rm = TRUE)) %>%
    print()
}
```

```{r}
plot_list <- list()

for (row in 1:nrow(var_grid_discrete)) {
  x = as.character(var_grid_discrete[row,'x'])
  y = as.character(var_grid_discrete[row,'y'])
  plot <- candidates %>%
    filter(!is.na(!!sym(x)),
           !is.na(!!sym(y))) %>%
    ggplot(aes(!!sym(y), color = !!sym(x))) +
    geom_freqpoly(bins = 10, show.legend=FALSE) +
    scale_color_manual(values = c('lightblue1','lightblue2',
                                  'lightblue3','lightblue4'))
  plot_list[[row]] <- plot
}

plot_grid(plotlist = plot_list, nrow = 3, ncol = 3)
```

```{r}
for (row in 1:nrow(var_grid_discrete)) {
  x = as.character(var_grid_discrete[row,'x'])
  y = as.character(var_grid_discrete[row,'y'])
  cat('Results for: ', y, ' ~ ', x, '\n')
  print(summary(aov(data = candidates, formula = as.formula(paste(y,'~',x)))))
  cat('\n')
}
```

## Linear Regression

```{r}
var_grid_continous <- data.frame(
  x = var_grid$x %>%
    str_remove_all('_binary'),
  y = var_grid$y %>%
    str_remove_all('_binary'))

results_df <- data.frame(var_grid_continous,
                         beta_coef = NA,
                         predictor_pval = NA,
                         r_squared = NA)

for (row in 1:nrow(var_grid_continous)) {
  x = as.character(var_grid_continous[row,'x'])
  y = as.character(var_grid_continous[row,'y'])
  
  model <- lm(data = candidates, formula = as.formula(paste(y,'~',x)))

  results_df <- results_df %>%
      mutate(
        beta_coef = replace(beta_coef,
                          x == as.character(var_grid_continous[row,'x']) &
                            y == as.character(var_grid_continous[row,'y']),
                          summary(model)$coefficients[2]),
        predictor_pval = replace(predictor_pval,
                           x == as.character(var_grid_continous[row,'x']) &
                             y == as.character(var_grid_continous[row,'y']),
                           summary(model)$coefficients[8]),
        r_squared = replace(r_squared,
                           x == as.character(var_grid_continous[row,'x']) &
                             y == as.character(var_grid_continous[row,'y']),
                          summary(model)$r.squared))
}

results_df %>% 
  filter(predictor_pval < 0.1) %>%
  arrange(desc(r_squared))

results_df %>%
  mutate(x = str_remove_all(x, 'compete|_'),
         y = str_remove_all(y, 'partisan_score|_')) %>% 
  ggplot(aes(factor(x, levels = c('cookpvi','ideology','effgap')), 
             factor(y, levels = c('twitter','govtrack','nominate')))) +
  # geom_tile(aes(fill = r_squared)) +
  geom_tile(aes(fill = ifelse(predictor_pval < 0.1, r_squared, NA))) +
  geom_text(aes(label = str_c('R^2: ',round(r_squared,3),
                              '\nPredictor pval: ',round(predictor_pval,3),
                              '\nBeta: ',round(beta_coef,3)))) +
  xlab('District Competition Measures') +
  ylab('Candidate Partisanship Measures') +
  scale_fill_gradient(low = 'gray100', 
                      high = 'darkslategray1',
                      na.value = 'grey50') + 
  theme(axis.text.y = element_text(angle = 90, hjust = 0.5)) +
  labs(fill = 'R^2')
```

