---
title: "Story 2 - The Fed's Dual Mandate"
author: "Keith Colella"
date: "2024-02-08"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(fredr)
library(blsAPI)
library(jsonlite)
library(lubridate)
library(zoo)
```

Read in API keys

```{r}
keys <- fromJSON('data/api_keys.json')
```

## Data

BLS API: https://www.bls.gov/developers/home.htm

```{r}
# https://www.bls.gov/cpi/overview.htm

year_ranges <- list(c('2005','2024'), c('1985','2005'))

cpi <- data.frame()
ue <- data.frame()

for (year_range in year_ranges){
  request <- list(
    'seriesid' = c('CUUR0000SA0L1E', 'LNS14000000'), 
    'startyear' = year_range[1], 'endyear' = year_range[2],
    'registrationkey' = keys$bls
  )
  
  response <- blsAPI(request) 
  json <- fromJSON(response)
  
  df1 <- json$Results$series$data[[1]]
  cpi <- rbind(cpi, df1[c('year', 'period', 'value')])
  
  df2 <- json$Results$series$data[[2]]
  ue <- rbind(ue, df2[c('year', 'period', 'value')])
}

cpi <- cpi %>%
  mutate(
    month = as.numeric(str_remove(period, 'M')),
    year = as.numeric(year),
    value = as.numeric(value)
  )

ue <- ue %>%
  mutate(
    month = as.numeric(str_remove(period, 'M')),
    year = as.numeric(year),
    value = as.numeric(value)
  )
```

FRED API: https://www.rdocumentation.org/packages/fredr/versions/2.1.0

```{r}
fredr_set_key(keys$fred)

fed_funds <- fredr(
  series_id = 'FEDFUNDS',
  observation_start = as.Date('1985-01-01'),
  observation_end = as.Date('2024-02-01')
)

fed_funds <- fed_funds %>%
  mutate(
    year = year(date),
    month = month(date)
  )

fed_target <- fredr(
  series_id = 'DFEDTARU',
  observation_start = as.Date('1985-01-01'),
  observation_end = as.Date('2024-02-01')
)

fed_target <- fed_target %>%
  mutate(
    year = year(date),
    month = month(date)
  )

recession <- fredr(
  series_id = 'JHDUSRGDPBR',
  observation_start = as.Date('1985-01-01'),
  observation_end = as.Date('2024-02-01')
)

recession <- recession %>%
  mutate(
    year = year(date),
    month = month(date)
  )

recession_dates <- recession %>%
  mutate(recession_start = value == 1 & lag(value) == 0,
         recession_end = value == 1 & lead(value) == 0) %>%
  replace_na(list(recession_start = TRUE)) %>%
  filter(recession_start | recession_end) %>%
  mutate(period_id = cumsum(recession_start)) %>%
  group_by(period_id) %>%
  summarise(start = min(date), end = max(date)) %>%
  ungroup()
```

MERGE

```{r}
df <- left_join(cpi, ue, by = c('year', 'month')) %>%
  left_join(fed_funds, by = c('year', 'month')) %>%
  left_join(fed_target, by = 'date') %>%
  rename(
    cpi = value.x, ue = value.y, 
    fed_funds = value.x.x, fed_target = value.y.y
  ) %>%
  select(date, cpi, ue, fed_funds, fed_target) %>%
  mutate(fed_target = 
           if_else(is.na(fed_target), ceiling(fed_funds * 4) / 4, fed_target)
  )

df
```

## Visualizations

Prep df

```{r}
df <- df %>%
  arrange(date) %>%
  mutate(cpi_growth = (cpi/lag(cpi, n = 12) - 1) * 100)

cpi_mean = mean(df$cpi)
cpi_sd = sd(df$cpi)

cpi_g_mean = mean(df$cpi_growth, na.rm = TRUE)
cpi_g_sd = sd(df$cpi_growth, na.rm = TRUE)

ue_mean = mean(df$ue)
ue_sd = sd(df$ue)

ff_mean = mean(df$fed_funds)
ff_sd = sd(df$fed_funds)
```

Levels

```{r}
df %>%
  pivot_longer(cols = c(cpi_growth, ue, fed_funds)) %>%
  ggplot(aes(date, value, color = name)) +
  geom_line() + 
  geom_rect(
    data = recession_dates, 
    aes(xmin = start, xmax = end, ymin = 0, ymax = 15),
    fill = 'blue', alpha = 0.3, inherit.aes = FALSE
  ) + 
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )
```

Normalized

```{r}
df %>%
  arrange(date) %>%
  mutate(
    cpi = (cpi - cpi_mean) / cpi_sd,
    ue = (ue - ue_mean) / ue_sd,
    fed_funds = (fed_funds - ff_mean) / ff_sd,
    cpi_growth = (cpi_growth - cpi_g_mean) / cpi_g_sd
  ) %>%
  pivot_longer(cols = c(cpi_growth, ue, fed_funds)) %>%
  ggplot(aes(date, value, color = name)) +
  geom_line() +
  geom_rect(
    data = recession_dates, 
    aes(xmin = start, xmax = end, ymin = -2, ymax = 4),
    fill = 'blue', alpha = 0.3, inherit.aes = FALSE
  ) + 
  scale_y_continuous(limits = c(-2,4)) +
  scale_x_date(limits = as.Date(c("1990-01-01", "2024-01-01"))) + 
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )
```

Normalized separate plots

```{r fig.height=5, fig.width=4}
df %>%
  arrange(date) %>%
  mutate(
    cpi = (cpi - cpi_mean) / cpi_sd,
    ue = (ue - ue_mean) / ue_sd,
    fed_funds = (fed_funds - ff_mean) / ff_sd,
    cpi_growth = (cpi_growth - cpi_g_mean) / cpi_g_sd
  ) %>%
  pivot_longer(cols = c(cpi_growth, ue, fed_funds)) %>%
  ggplot(aes(date, value)) + # color = name
  geom_line() +
  geom_rect(
    data = recession_dates, 
    aes(xmin = start, xmax = end, ymin = -2, ymax = 4),
    fill = 'blue', alpha = 0.3, inherit.aes = FALSE
  ) +
  facet_wrap(~name, ncol = 1) + 
  scale_y_continuous(limits = c(-4,4)) +
  scale_x_date(limits = as.Date(c("1990-01-01", "2024-01-01"))) + 
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )
```

Separate CPI and UE

```{r}
df %>%
  arrange(date) %>%
  mutate(
    cpi = (cpi - cpi_mean) / cpi_sd,
    ue = (ue - ue_mean) / ue_sd,
    fed_funds = (fed_funds - ff_mean) / ff_sd,
    cpi_growth = (cpi_growth - cpi_g_mean) / cpi_g_sd
  ) %>%
  pivot_longer(cols = c(cpi_growth, fed_funds)) %>%
  ggplot(aes(date, value, color = name)) +
  geom_line() +
  geom_rect(
    data = recession_dates, 
    aes(xmin = start, xmax = end, ymin = -2, ymax = 4),
    fill = 'blue', alpha = 0.3, inherit.aes = FALSE
  ) +
  scale_y_continuous(limits = c(-2,4)) +
  scale_x_date(limits = as.Date(c("1990-01-01", "2024-01-01"))) + 
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

df %>%
  arrange(date) %>%
  mutate(
    cpi = (cpi - cpi_mean) / cpi_sd,
    ue = (ue - ue_mean) / ue_sd,
    fed_funds = (fed_funds - ff_mean) / ff_sd,
    cpi_growth = (cpi_growth - cpi_g_mean) / cpi_g_sd
  ) %>%
  pivot_longer(cols = c(ue, fed_funds)) %>%
  ggplot(aes(date, value, color = name)) +
  geom_line() +
  geom_rect(
    data = recession_dates, 
    aes(xmin = start, xmax = end, ymin = -2, ymax = 4),
    fill = 'blue', alpha = 0.3, inherit.aes = FALSE
  ) + 
  scale_y_continuous(limits = c(-2,4)) +
  scale_x_date(limits = as.Date(c("1990-01-01", "2024-01-01"))) + 
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )
```

```{r}
df %>%
  pivot_longer(cols = c(cpi_growth, fed_funds)) %>%
  ggplot(aes(date, value, color = name)) +
  geom_line() +
  geom_rect(
    data = recession_dates, 
    aes(xmin = start, xmax = end, ymin = 0, ymax = 15),
    fill = 'blue', alpha = 0.3, inherit.aes = FALSE
  ) +
  scale_x_date(limits = as.Date(c("1990-01-01", "2024-01-01"))) + 
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

df %>%
  pivot_longer(cols = c(ue, fed_funds)) %>%
  ggplot(aes(date, value, color = name)) +
  geom_line() +
  geom_rect(
    data = recession_dates, 
    aes(xmin = start, xmax = end, ymin = 0, ymax = 15),
    fill = 'blue', alpha = 0.3, inherit.aes = FALSE
  ) + 
  scale_x_date(limits = as.Date(c("1990-01-01", "2024-01-01"))) + 
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )
```

Optimal Lag

```{r}
cpi_ccf <- ccf(
  as.ts(df$fed_funds), as.ts(df$cpi_growth), 
  na.action = na.pass, plot = FALSE
)
max_corr_index <- which.max(abs(cpi_ccf$acf))
cpi_lag <- cpi_ccf$lag[max_corr_index]

df %>%
  mutate(cpi_growth = lag(cpi_growth, n = cpi_lag)) %>%
  pivot_longer(cols = c(cpi_growth, fed_funds)) %>%
  ggplot(aes(date, value, color = name)) +
  geom_line() +
  geom_rect(
    data = recession_dates, 
    aes(xmin = start, xmax = end, ymin = 0, ymax = 15),
    fill = 'blue', alpha = 0.3, inherit.aes = FALSE
  ) +
  scale_x_date(limits = as.Date(c("1990-01-01", "2024-01-01"))) + 
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )
```

```{r}
ue_ccf <- ccf(
  as.ts(df$fed_funds), as.ts(df$ue), 
  na.action = na.pass, plot = FALSE
)
max_corr_index <- which.max(abs(ue_ccf$acf))
ue_lag <- ue_ccf$lag[max_corr_index]

df %>%
  mutate(ue = lag(ue, n = ue_lag)) %>%
  pivot_longer(cols = c(ue, fed_funds)) %>%
  ggplot(aes(date, value, color = name)) +
  geom_line() +
  geom_rect(
    data = recession_dates, 
    aes(xmin = start, xmax = end, ymin = 0, ymax = 15),
    fill = 'blue', alpha = 0.3, inherit.aes = FALSE
  ) +
  scale_x_date(limits = as.Date(c("1990-01-01", "2024-01-01"))) + 
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )
```

Bar Charts

```{r}
df <- df %>%
  mutate(
    fed_roll_peak = rollapply(
      fed_target, width = 52, FUN = max, 
      align = "center", fill = c(NA, NA, 'extend')
    ),
    fed_roll_valley = rollapply(
      fed_target, width = 52, FUN = min, 
      align = "center", fill = c(NA, NA, 'extend')
    ),
    fed_status = case_when(
      fed_target == fed_roll_peak & fed_target > lead(fed_target) ~ 'peak',
      fed_target == fed_roll_valley & fed_target < lead(fed_target)~ 'valley',
      .default = 'between'
    )) %>%
  select(-fed_roll_peak, -fed_roll_valley)

previous_cycle <- 'hike'
current_cycle <- 'hike'

for (row in 1:nrow(df)) {
  if (df[row, 'fed_status'] == 'peak') {current_cycle <- 'cut'}
  if (df[row, 'fed_status'] == 'valley') {current_cycle <- 'hike'}
  
  lags <- c(df[row, 'fed_target'])
  
  for (lag in 1:12) {
    lags <- c(lags, df[row-lag, 'fed_target'])
  }
  
  if (all(diff(lags) == 0)) {
    df[row, 'fed_status'] <- 'maintain'
  } else if (current_cycle == 'cut' & previous_cycle != 'cut') {
    df[row, 'fed_status'] <- 'start_cut'
  } else if (current_cycle == 'hike' & previous_cycle != 'hike') {
    df[row, 'fed_status'] <- 'start_hike'
  } else if (current_cycle == 'cut' & previous_cycle == 'cut') {
    df[row, 'fed_status'] <- 'cut'
  } else if (current_cycle == 'hike' & previous_cycle == 'hike') {
    df[row, 'fed_status'] <- 'hike'
  }
  
  previous_cycle <- current_cycle
}

df[nrow(df), 'fed_status'] <- 'cut'
# df[df$date > '2019-07-01' & df$date < '2020-04-01', 'fed_status'] <- 'hike'
# df[df$date == '2020-04-01', 'fed_status'] <- 'start_cut'

ggplot() + 
  geom_rect(data = df, aes(
    xmin = date, xmax = lead(date, order_by = date), 
    ymin = -Inf, ymax = Inf, fill = fed_status
  ), alpha = 0.4) +
  geom_line(data = df, aes(x = date, y = fed_target), color = "black") +
  geom_line(data = df, aes(x = date, y = fed_funds), color = "green") +
  # geom_line(data = df, aes(x = date, y = ue), color = "red") +
  # geom_line(data = df, aes(x = date, y = cpi_growth), color = "blue") +
  scale_fill_manual(values = c("cut" = "red", "hike" = "green"))

df %>%
  filter(str_detect(fed_status, 'start'))

df
```

```{r}
cut_cycles <- data.frame(
  start = as.Date(c('1989-05-01','1995-05-01','2000-07-01','2007-03-01','2019-07-01')),
  end = as.Date(c('1992-12-01','1999-01-01','2004-01-01','2010-01-01','2020-04-01'))
)

cut_cycles

hike_cycles <- data.frame(
  start = as.Date(c('1992-12-01','1999-01-01','2004-01-01','2016-01-01','2022-04-01')),
  end = as.Date(c('1995-05-01','2000-07-01','2007-03-01','2019-07-01','2024-01-01'))
)

hike_cycles

ggplot() + 
  # geom_line(data = df, aes(x = date, y = fed_target), color = "black") +
  # geom_line(data = df, aes(x = date, y = fed_funds), color = "green") +
  geom_line(data = df, aes(x = date, y = ue), color = "red") +
  geom_line(data = df, aes(x = date, y = cpi_growth), color = "blue") +
  geom_rect(
    data = cut_cycles, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), 
    alpha = 0.3, fill = 'red', inherit.aes = FALSE
  ) +
  geom_rect(
    data = hike_cycles, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), 
    alpha = 0.3, fill = 'blue', inherit.aes = FALSE
  )
```

```{r}
for (row in 1:nrow(cut_cycles)) {
  
  time_to_change <- as.period(hike_cycles[row, 2] - cut_cycles[row, 2])
  obs_period <- if_else(time_to_change < months(60), time_to_change, months(60))
  
  cut_cycles[row, 'obs_period_end'] <- cut_cycles[row, 2] + obs_period
  
  cut_cycles[row, 'ff_change'] <- 
    df[df$date == cut_cycles[row, 2], 'fed_funds'] - 
    df[df$date == cut_cycles[row, 1], 'fed_funds']
  
  cut_cycles[row, 'infl_change'] <- 
    df[df$date == cut_cycles[row, 2] + obs_period, 'cpi_growth'] -
    df[df$date == cut_cycles[row, 2], 'cpi_growth']
    # NA
  
  cut_cycles[row, 'ue_change'] <- 
    df[df$date == cut_cycles[row, 2] + obs_period, 'ue'] - 
    df[df$date == cut_cycles[row, 2], 'ue']
}

cut_cycles

for (row in 1:nrow(hike_cycles)) {
  
  if (row == nrow(hike_cycles)) {
    obs_period <- 0
    adjustment <- 1
  } else {
    time_to_change <- as.period(cut_cycles[row+1, 2] - hike_cycles[row, 2])
    obs_period <- if_else(time_to_change < months(60), time_to_change, months(60))
    adjustment <- 0
  }
  
  hike_cycles[row, 'obs_period_end'] <- hike_cycles[row, 2] + obs_period
  
  hike_cycles[row, 'ff_change'] <- 
    df[df$date == hike_cycles[row, 2], 'fed_funds'] - 
    df[df$date == hike_cycles[row, 1], 'fed_funds']
  
  hike_cycles[row, 'infl_change'] <- 
    df[df$date == hike_cycles[row, 2] + obs_period, 'cpi_growth'] - 
    df[df$date == hike_cycles[row, 2 - adjustment], 'cpi_growth']
  
  hike_cycles[row, 'ue_change'] <- 
    df[df$date == hike_cycles[row, 2] + obs_period, 'ue'] -
    df[df$date == hike_cycles[row, 2 - adjustment], 'ue']
    # NA
}

hike_cycles
```


```{r}
cut_cycles %>%
  pivot_longer(cols = c(ff_change, ue_change)) %>% 
  mutate(
    end = as.character(end),
    value = (value)
  ) %>%
  ggplot(aes(end, value, fill = name)) +
  geom_col(position = position_dodge()) +
  theme_minimal()

hike_cycles %>%
  mutate(
    end = as.character(end),
    infl_change = -(infl_change)
  ) %>%
  pivot_longer(cols = c(ff_change, infl_change)) %>% 
  ggplot(aes(end, value, fill = name)) +
  geom_col(position = position_dodge()) +
  theme_minimal()
```


```{r}
rbind(cut_cycles, hike_cycles) %>%
  mutate(
    end = as.character(end),
    infl_change = (infl_change),
    effect = coalesce(infl_change, ue_change)
  ) %>%
  # pivot_longer(cols = c(ff_change, effect)) %>%
  pivot_longer(cols = c(ff_change, infl_change, ue_change), values_drop_na = TRUE) %>% 
  ggplot(aes(end, value, fill = name)) +
  geom_col(position = position_dodge()) +
  # geom_line(data = df, aes(x = date, y = ue), color = "red", inherit.aes = FALSE)
  theme_minimal()
```

```{r}
# Sample data
df1 <- data.frame(
  category = c("A", "B", "C"),
  start = as.Date(c("2021-01-01", "2021-02-01", "2021-03-01")),
  end = as.Date(c("2021-01-15", "2021-02-20", "2021-04-01"))
)

# Calculate duration and mid-point for plotting
df1$duration <- as.numeric(df1$end - df1$start)
df1$mid_point <- df1$start + (df1$duration / 2)

ggplot(df1, aes(x = mid_point, y = category, height = 0.9, width = duration)) +
  geom_tile(fill = "steelblue") +
  scale_x_date(name = "Date", date_breaks = "1 month", date_labels = "%b %Y") +
  labs(y = "Category", title = "Duration of Events by Category") +
  theme_minimal()

```

